""" Provides visualizations for the word embedding model generated by Word2Vec
"""

from gensim.models import Word2Vec
import logging  # Setting up the loggings to monitor gensim
from gensim.models.callbacks import CallbackAny2Vec
from gensim.test.utils import get_tmpfile
from featurization.word2vec import EpochSaver
from gensim.models import KeyedVectors
import constants
import constants

def main():

    wv = KeyedVectors.load('../w2v.wv')
    ms = wv.most_similar(positive=["san"])
    print(ms)




if __name__ == "__main__":
    main()